name: Pickle tester
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest]
        #python-version: ['pypy3.9', '3.9', '3.10']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' #${{matrix.python-version}}
          architecture: 'x64'
          
      - name: Install dependencies
        run: |         
          brew install gettext
          brew link gettext --force
          pip install --upgrade pip
    
      - name: Run tests
        run: python -m unittest pickle_test
            