name: Pickle tester
on: [push, pull_request]
permissions:
  contents: write
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        #python-version: ['pypy3.9', '3.9', '3.10']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' #${{matrix.python-version}}
          
      - name: Install dependencies
        run: |         
          pip install --upgrade pip

      - name: Run tests
        run: |
          python -m unittest pickle_test

      - name: Upload test artifacts
        uses: actions/upload-artifacts@v2
        with:
          name: pickle-test-results
          path: |
            pickle_bool_*.pkl
            pickle_class_*.pkl
            pickle_dict_*.pkl
            pickle_float_accuracy_*.pkl
            pickle_float_*.pkl
            pickle_func_*.pkl
            pickle_instance_*.pkl
            pickle_int_*.pkl
            pickle_list_*.pkl
            pickle_string_*.pkl 
        #   git config user.name 'github-actions'
        #   git config user.email 'github-actions@github.com'
        #   git pull
        #   git add *.pkl
        #   git commit -am "Generated files"
        #   git push
            